version: '3.8'

services:
  db:
    image: postgres:15
    container_name: ecommerce_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ecom
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d ecom"]
      interval: 30s
      timeout: 10s
      retries: 5

  api:
    build: .
    container_name: ecommerce_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/ecom
      - ENVIRONMENT=development
    volumes:
      - ./app:/app/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ecommerce_network

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin4_container
  #   restart: always
  #   ports:
  #     - "8888:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
  #     PGADMIN_DEFAULT_PASSWORD: strong-password
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin


volumes:
  postgres_data:
  #pgadmin-data:

networks:
  ecommerce_network:
    driver: bridge